### ISSUE TITLE
Fly Y CORRECTION

### ISSUE THREAD

**Issue by Shiginima** [jaszlo/Playerautoma#27] opened 2024-10-28 03:01 UTC
whenever im using /fly flying lets say y108.500 after starting reply it will go down to 108 every time but sometimes out of nowhere it will go down to 107.6130 and then it corrects again to 107 this way im going lower and lower for some reason which is kind of annoying can you fix that somehow add an option to disable that Y correction?

**Comment by jaszlo** [comment] 2024-10-29 13:22
This is most likely because your replay isn't an accurate loop and gets out of sync.

In general I need to center the player at the start of the replay. Without it even the first replay would be out of sync.

I can add the option to position the player not at the center but at the position at which the recording was started. But without some sort of position fixing at the start of the replay the mod is completly useless. 

Thank you for your feedback.

**Comment by Shiginima** [comment] 2024-11-17 17:24
You sure this centering won’t trigger anticheats?   This is most likely because your replay isn&#39;t an accurate loop and gets out of sync. In general I need to center the player at the start of the replay. Without it even the first replay would be out of sync. I can add the option to position the player not at the center but at the position at which the recording was started. But without some sort of position fixing at the start of the replay the mod is completly useless. Thank you for your feedback. —  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .  You are receiving this because you authored the thread. Message ID:  &lt;jaszlo/Playerautoma/issues/27/2444218812 @ github . com&gt;

**Comment by jaszlo** [comment] 2024-11-22 10:14
I don't care if it triggers anticheat. I explicitly state that the mod can be regarded as cheating by servers. It's not my intention to work around that.

**Comment by jaszlo** [comment] 2024-11-22 10:19
I would in general not recommend creating to fast or complex replays as those can get out of sync. I was not able to reproduce this and therefore will close the Issue. If you have further question please contact me on Discord

**Closed by jaszlo** 2024-11-22 10:19 UTC
Labels: enhancement

**Comment by Shiginima** [comment] 2024-11-24 04:48
> I would in general not recommend creating to fast or complex replays as those can get out of sync. I was not able to reproduce this and therefore will close the Issue. If you have further question please contact me on Discord

i messaged you on idsocrd c heck your inbox or spam
